### ISSUE TITLE
总结一下对 CheckBox 的相关操作

### ISSUE THREAD

**Issue by mcya** [yaolingersi/JavaScriptExperience#69]
### 总结一下对 CheckBox 的相关操作

**Comment by mcya** [comment]
### html

#### 文字选框联动 - `input`的id值和`label`的for值相同
```html
<input style="vertical-align:middle; margin-top:0;" type="checkbox" value='ABC' id='DICTID'  />
<label for='DICTID'>DICTNAME</label>
```
------------------

```js
if (array && array.length>0) {
	for (var i = 0; i < array.length; i++) {
		$("#queryForm #lungangTableId #groupCheckBoxId").append('<input style="vertical-align:middle; margin-top:0;" type="checkbox" value='+array[i].DICTID+' id='+array[i].DICTID+' dictname='+array[i].DICTNAME+' /><label class="labels" for='+array[i].DICTID+'>'+array[i].DICTNAME+'</label>')
	}
}
```

```html
<input style="vertical-align:middle; margin-top:0;" type="checkbox" value='+array[i].DICTID+' id='+array[i].DICTID+' dictname='+array[i].DICTNAME+' />
<label class="labels" for='+array[i].DICTID+'>'+array[i].DICTNAME+'</label>
```

**Comment by mcya** [comment]
### CheckBox 自定义样式

```css
input[type="checkbox"] + label::before {
    content: "\a0";
    display: inline-block;
    vertical-align: .2em;
    width: .8em;
    height: .8em;
    margin-right: .2em;
    border-radius: .2em;
    background-color: silver;
    text-indent: .15em;
    line-height: .65;
}
input[type="checkbox"]:checked + label::before {
    content: "\2713";
    background-color: yellowgreen;
}
input[type="checkbox"] {/*清空原先样式*/
	position: absolute;
  clip: rect(0, 0, 0, 0);
	display: inline-block;
}

input[type="checkbox"]:focus + label::before {
    box-shadow: 0 0 .1em .1em #58a;
}
input[type="checkbox"]:disabled + label::before { /*disabled*/
    background-color: gray;
    box-shadow: none;
    color: #555;
}
```
