### ISSUE TITLE
work something

### ISSUE THREAD

**Issue by mcya** [yaolingersi/JavaScriptExperience#87]
work something

**Comment by mcya** [comment]
```css
/* 暗黑模式 - 反转所有颜色, 不支持IE */
html[theme='dark-mode'] {
    filter: invert(1) hue-rotate(180deg);
}
/*
filter CSS 属性将模糊或颜色偏移等图形效果应用于元素。滤镜通常用于调整图像，背景和边框的渲染。
对于暗黑模式，将使用两个 filter ：invert 和 hue-rotate
invert：反转配色。黑色变为白色，白色变为黑色，所有颜色都是如此
hue-rotate：帮助我们处理所有其他非黑色和白色的颜色。将色相旋转180度，我们确保应用程序的颜色主题不会改变，而只是减弱其颜色。

缺点是，它还会反转应用程序中的所有图像
*/

/* 可以添加黑白切换动画缓冲效果 */
html {
  transition: color 300ms, background-color 300ms;
}
```

```js
// "lodash": "^4.13.1",
// lodash 常用函数

// 必填校验
import _isEmpty from 'lodash/isEmpty'

// 深拷贝
import _cloneDeep from 'lodash/cloneDeep'

// 从数组中删除
import _remove from 'lodash/remove';

import _uniqBy from 'lodash/uniqBy';
```
